#!/bin/bash
# takes the name of a file and returns a markdown-syntax to it (grabbing the "name" in the yaml metadata to populate the link")

# assume filename passed in on $1

name=$(cat $1 | sed -En "2s/name:\ (.*)$/\\1/p")

echo "[$name]($1)"
